---
 - name: add the hadoopmaster host file entry
   lineinfile: dest=/etc/hosts line='{{ hadoopmaster_ip }} hadoopmaster' owner=root group=root mode=0644

 - name: add the hadoopslave host file entry
   lineinfile: dest=/etc/hosts line='{{ hadoopslave_ip }} hadoopslave' owner=root group=root mode=0644
