#! /bin/sh
### BEGIN INIT INFO
# Provides: tomcat2
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Tomcat
# Description: This file starts and stops Tomcat server
# 
### END INIT INFO

TOMCAT_DIR=/usr/local/apache-tomcat-7.0.73-2
export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_05

case "$1" in
 start)
   su vagrant -c $TOMCAT_DIR/bin/startup.sh
   ;;
 stop)
   su vagrant -c $TOMCAT_DIR/bin/shutdown.sh
   sleep 10
   ;;
 restart)
   su vagrant -c $TOMCAT_DIR/bin/shutdown.sh
   sleep 20
   su vagrant -c $TOMCAT_DIR/bin/startup.sh
   ;;
 *)
   echo "Usage: tomcat2 {start|stop|restart}" >&2
   exit 3
   ;;
esac