#! /bin/sh
### BEGIN INIT INFO
# Provides: Hadoop yarn
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: hadoop yarn
# Description: This file starts and stops yarn service
# 
### END INIT INFO

HADOOP_DIR=/usr/local/hadoop-2.6.0
export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_05

case "$1" in
 start)
   su vagrant -c $HADOOP_DIR/sbin/start-yarn.sh
   ;;
 stop)
   su vagrant -c $HADOOP_DIR/sbin/stop-yarn.sh
   sleep 10
   ;;
 restart)
   su vagrant -c $HADOOP_DIR/sbin/stop-yarn.sh
   sleep 20
   su vagrant -c $HADOOP_DIR/sbin/start-yarn.sh
   ;;
 *)
   echo "Usage: hadoop-yarn {start|stop|restart}" >&2
   exit 3
   ;;
esac
